// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgoejcgdmayjjjldpnur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impnb2VqY2dkbWF5ampqbGRwbnVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2Mzg1MDksImV4cCI6MjA3MDIxNDUwOX0.iIE3dOqDdXPIX1UB__EjQYas1AHaxrdrOA99ibLCm8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with consistent headers for edge function compatibility
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      // Ensure consistent branch/environment headers with edge functions
      ...(typeof window !== 'undefined' && window.location.search.includes('branch=') && {
        'x-supabase-branch': new URLSearchParams(window.location.search).get('branch') || ''
      })
    }
  }
});